### ISSUE TITLE
Bad Login Verification

### ISSUE THREAD

**Issue by JLaFrance3** [PeterZegarek/QuinnipiacMarketplace#6]
Line 62 of qBay.java does not properly account for capitalization. The .toLowerCase() method is incorrectly placed on the stored information rather than user entered information.

'''

                //Validate email
                if(userEmail.equals(studentLogins[i][0].toLowerCase())) {

                    //Validate associated password
                    if(userPW.equals(studentLogins[i][1])) {
                        loginValid = true;  //Correct email and password
                    }
                }

'''

**Comment by JLaFrance3** [comment]
Generous fix from BlakeNorman12. Closing issue.

**Comment by PeterZegarek** [comment]
Very interesting. Nice catch
